# Generated by Django 3.2 on 2021-05-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='date_push',
        ),
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulaire.formulaire')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='submission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formulaire.submission'),
        ),
    ]
