# Generated by Django 3.2 on 2021-06-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_auto_20210512_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
